name: Manual Mapper Pro Derleyici

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Kodları Çek
        uses: actions/checkout@v4

      - name: MSVC (C++) Kurulumu
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Injector ve DLL Derle
        shell: cmd
        run: |
          cl.exe /EHsc /O2 /std:c++17 /MT main.cpp /link user32.lib /out:Injector.exe
          cl.exe /LD /O2 /std:c++17 /MT cheat.cpp /link user32.lib /out:cheat.dll

      - name: Dosyaları Hazırla
        shell: cmd
        run: |
          mkdir Pro-Set
          move Injector.exe Pro-Set\
          move cheat.dll Pro-Set\

      - name: Paketi Yukle
        uses: actions/upload-artifact@v4
        with:
          name: Hile-Paketi
          path: Pro-Set/
          
