name: Windows EXE ve DLL Derleyici

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Kodları Çek
        uses: actions/checkout@v4

      - name: MSVC (C++) Kurulumu
        uses: ilammy/msvc-dev-cmd@v1

      - name: Injector Derle
        run: cl.exe /EHsc main.cpp user32.lib /fe:Injector.exe

      - name: DLL Derle
        run: cl.exe /LD cheat.cpp user32.lib /fe:cheat.dll

      - name: Dosyaları Klasöre Topla
        run: |
          mkdir hile_paketi
          move Injector.exe hile_paketi\
          move cheat.dll hile_paketi\

      - name: Paketi Yukle
        uses: actions/upload-artifact@v4
        with:
          name: Derlenmis-Hile-Seti
          path: hile_paketi/
          
